openapi: 3.0.3
info:
  title: IZ Project API
  version: 1.0.0
  description: Документация публичных эндпоинтов.
paths:
  /api/cars/:
    get:
      operationId: cars_list
      parameters:
      - in: query
        name: body_type
        schema:
          type: string
      - in: query
        name: make
        schema:
          type: string
      - in: query
        name: model
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: price_max
        schema:
          type: number
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - in: query
        name: transmission
        schema:
          type: string
      - in: query
        name: year_max
        schema:
          type: integer
      - in: query
        name: year_min
        schema:
          type: integer
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCarList'
          description: ''
  /api/cars/{slug}/:
    get:
      operationId: cars_retrieve
      parameters:
      - in: path
        name: slug
        schema:
          type: string
          pattern: ^[-a-zA-Z0-9_]+$
        required: true
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        images:
          type: array
          items:
            $ref: '#/components/schemas/CarImage'
          readOnly: true
        title:
          type: string
          maxLength: 200
        make:
          type: string
          maxLength: 100
        model:
          type: string
          maxLength: 100
        year:
          type: integer
          maximum: 32767
          minimum: 0
        body_type:
          type: string
          maxLength: 50
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        stock_no:
          type: string
          maxLength: 50
        mileage:
          type: integer
          maximum: 2147483647
          minimum: 0
        interior:
          type: string
          maxLength: 100
        exterior:
          type: string
          maxLength: 100
        vin:
          type: string
          maxLength: 32
        transmission:
          type: string
          maxLength: 50
        engine:
          type: string
          maxLength: 100
        description:
          type: string
        slug:
          type: string
          maxLength: 220
          pattern: ^[-a-zA-Z0-9_]+$
        is_published:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
      required:
      - body_type
      - created
      - id
      - images
      - make
      - model
      - price
      - title
      - updated
      - vin
      - year
    CarImage:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image:
          type: string
          format: uri
        alt:
          type: string
          maxLength: 150
        order:
          type: integer
          maximum: 32767
          minimum: 0
      required:
      - id
      - image
    PaginatedCarList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Car'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
servers:
- url: https://iztestproject.icu
  description: prod
