# Generated by Django 5.2.6 on 2025-10-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='cars_car_make_3ceb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='cars_car_year_fc6735_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['body_type'], name='cars_car_body_ty_1cdbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_published', 'is_sold'], name='cars_car_is_publ_3a5294_idx'),
        ),
    ]
