# Generated by Django 5.2.6 on 2025-09-24 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contact', 'Contact'), ('financing', 'Financing'), ('shipping', 'Shipping'), ('car', 'Car lead')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
